/*
 * This file is generated by jOOQ.
 */
package app.cta4j.jooq.tables;


import app.cta4j.jooq.Keys;
import app.cta4j.jooq.Public;
import app.cta4j.jooq.tables.Route.RoutePath;
import app.cta4j.jooq.tables.RouteDirection.RouteDirectionPath;
import app.cta4j.jooq.tables.RouteStop.RouteStopPath;
import app.cta4j.jooq.tables.records.DirectionRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Direction extends TableImpl<DirectionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.direction</code>
     */
    public static final Direction DIRECTION = new Direction();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<DirectionRecord> getRecordType() {
        return DirectionRecord.class;
    }

    /**
     * The column <code>public.direction.id</code>.
     */
    public final TableField<DirectionRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>public.direction.name</code>.
     */
    public final TableField<DirectionRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    private Direction(Name alias, Table<DirectionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Direction(Name alias, Table<DirectionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.direction</code> table reference
     */
    public Direction(String alias) {
        this(DSL.name(alias), DIRECTION);
    }

    /**
     * Create an aliased <code>public.direction</code> table reference
     */
    public Direction(Name alias) {
        this(alias, DIRECTION);
    }

    /**
     * Create a <code>public.direction</code> table reference
     */
    public Direction() {
        this(DSL.name("direction"), null);
    }

    public <O extends Record> Direction(Table<O> path, ForeignKey<O, DirectionRecord> childPath, InverseForeignKey<O, DirectionRecord> parentPath) {
        super(path, childPath, parentPath, DIRECTION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class DirectionPath extends Direction implements Path<DirectionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> DirectionPath(Table<O> path, ForeignKey<O, DirectionRecord> childPath, InverseForeignKey<O, DirectionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private DirectionPath(Name alias, Table<DirectionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public DirectionPath as(String alias) {
            return new DirectionPath(DSL.name(alias), this);
        }

        @Override
        public DirectionPath as(Name alias) {
            return new DirectionPath(alias, this);
        }

        @Override
        public DirectionPath as(Table<?> alias) {
            return new DirectionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public Identity<DirectionRecord, Integer> getIdentity() {
        return (Identity<DirectionRecord, Integer>) super.getIdentity();
    }

    @Override
    public UniqueKey<DirectionRecord> getPrimaryKey() {
        return Keys.DIRECTION_PKEY;
    }

    private transient RouteDirectionPath _routeDirection;

    /**
     * Get the implicit to-many join path to the
     * <code>public.route_direction</code> table
     */
    public RouteDirectionPath routeDirection() {
        if (_routeDirection == null)
            _routeDirection = new RouteDirectionPath(this, null, Keys.ROUTE_DIRECTION__ROUTE_DIRECTION_DIRECTION_ID_FKEY.getInverseKey());

        return _routeDirection;
    }

    private transient RouteStopPath _routeStop;

    /**
     * Get the implicit to-many join path to the <code>public.route_stop</code>
     * table
     */
    public RouteStopPath routeStop() {
        if (_routeStop == null)
            _routeStop = new RouteStopPath(this, null, Keys.ROUTE_STOP__ROUTE_STOP_DIRECTION_ID_FKEY.getInverseKey());

        return _routeStop;
    }

    /**
     * Get the implicit many-to-many join path to the <code>public.route</code>
     * table
     */
    public RoutePath route() {
        return routeDirection().route();
    }

    @Override
    public Direction as(String alias) {
        return new Direction(DSL.name(alias), this);
    }

    @Override
    public Direction as(Name alias) {
        return new Direction(alias, this);
    }

    @Override
    public Direction as(Table<?> alias) {
        return new Direction(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Direction rename(String name) {
        return new Direction(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Direction rename(Name name) {
        return new Direction(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Direction rename(Table<?> name) {
        return new Direction(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Direction where(Condition condition) {
        return new Direction(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Direction where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Direction where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Direction where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Direction where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Direction where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Direction where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Direction where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Direction whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Direction whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
