/*
 * This file is generated by jOOQ.
 */
package app.cta4j.jooq.tables;


import app.cta4j.jooq.Keys;
import app.cta4j.jooq.Public;
import app.cta4j.jooq.tables.Direction.DirectionPath;
import app.cta4j.jooq.tables.Route.RoutePath;
import app.cta4j.jooq.tables.records.RouteDirectionRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Arrays;
import java.util.Collection;
import java.util.List;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class RouteDirection extends TableImpl<RouteDirectionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.route_direction</code>
     */
    public static final RouteDirection ROUTE_DIRECTION = new RouteDirection();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<RouteDirectionRecord> getRecordType() {
        return RouteDirectionRecord.class;
    }

    /**
     * The column <code>public.route_direction.route_id</code>.
     */
    public final TableField<RouteDirectionRecord, String> ROUTE_ID = createField(DSL.name("route_id"), SQLDataType.VARCHAR(4).nullable(false), this, "");

    /**
     * The column <code>public.route_direction.direction_id</code>.
     */
    public final TableField<RouteDirectionRecord, Integer> DIRECTION_ID = createField(DSL.name("direction_id"), SQLDataType.INTEGER.nullable(false), this, "");

    private RouteDirection(Name alias, Table<RouteDirectionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private RouteDirection(Name alias, Table<RouteDirectionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.route_direction</code> table reference
     */
    public RouteDirection(String alias) {
        this(DSL.name(alias), ROUTE_DIRECTION);
    }

    /**
     * Create an aliased <code>public.route_direction</code> table reference
     */
    public RouteDirection(Name alias) {
        this(alias, ROUTE_DIRECTION);
    }

    /**
     * Create a <code>public.route_direction</code> table reference
     */
    public RouteDirection() {
        this(DSL.name("route_direction"), null);
    }

    public <O extends Record> RouteDirection(Table<O> path, ForeignKey<O, RouteDirectionRecord> childPath, InverseForeignKey<O, RouteDirectionRecord> parentPath) {
        super(path, childPath, parentPath, ROUTE_DIRECTION);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class RouteDirectionPath extends RouteDirection implements Path<RouteDirectionRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> RouteDirectionPath(Table<O> path, ForeignKey<O, RouteDirectionRecord> childPath, InverseForeignKey<O, RouteDirectionRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private RouteDirectionPath(Name alias, Table<RouteDirectionRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public RouteDirectionPath as(String alias) {
            return new RouteDirectionPath(DSL.name(alias), this);
        }

        @Override
        public RouteDirectionPath as(Name alias) {
            return new RouteDirectionPath(alias, this);
        }

        @Override
        public RouteDirectionPath as(Table<?> alias) {
            return new RouteDirectionPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<RouteDirectionRecord> getPrimaryKey() {
        return Keys.ROUTE_DIRECTION_PKEY;
    }

    @Override
    public List<ForeignKey<RouteDirectionRecord, ?>> getReferences() {
        return Arrays.asList(Keys.ROUTE_DIRECTION__ROUTE_DIRECTION_DIRECTION_ID_FKEY, Keys.ROUTE_DIRECTION__ROUTE_DIRECTION_ROUTE_ID_FKEY);
    }

    private transient DirectionPath _direction;

    /**
     * Get the implicit join path to the <code>public.direction</code> table.
     */
    public DirectionPath direction() {
        if (_direction == null)
            _direction = new DirectionPath(this, Keys.ROUTE_DIRECTION__ROUTE_DIRECTION_DIRECTION_ID_FKEY, null);

        return _direction;
    }

    private transient RoutePath _route;

    /**
     * Get the implicit join path to the <code>public.route</code> table.
     */
    public RoutePath route() {
        if (_route == null)
            _route = new RoutePath(this, Keys.ROUTE_DIRECTION__ROUTE_DIRECTION_ROUTE_ID_FKEY, null);

        return _route;
    }

    @Override
    public RouteDirection as(String alias) {
        return new RouteDirection(DSL.name(alias), this);
    }

    @Override
    public RouteDirection as(Name alias) {
        return new RouteDirection(alias, this);
    }

    @Override
    public RouteDirection as(Table<?> alias) {
        return new RouteDirection(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public RouteDirection rename(String name) {
        return new RouteDirection(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public RouteDirection rename(Name name) {
        return new RouteDirection(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public RouteDirection rename(Table<?> name) {
        return new RouteDirection(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RouteDirection where(Condition condition) {
        return new RouteDirection(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RouteDirection where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RouteDirection where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RouteDirection where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RouteDirection where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RouteDirection where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RouteDirection where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public RouteDirection where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RouteDirection whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public RouteDirection whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
