/*
 * This file is generated by jOOQ.
 */
package app.cta4j.jooq.tables;


import app.cta4j.jooq.Keys;
import app.cta4j.jooq.Public;
import app.cta4j.jooq.tables.RouteStop.RouteStopPath;
import app.cta4j.jooq.tables.records.StopRecord;
import org.jooq.Record;
import org.jooq.*;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

import java.util.Collection;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Stop extends TableImpl<StopRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.stop</code>
     */
    public static final Stop STOP = new Stop();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<StopRecord> getRecordType() {
        return StopRecord.class;
    }

    /**
     * The column <code>public.stop.id</code>.
     */
    public final TableField<StopRecord, Integer> ID = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "");

    /**
     * The column <code>public.stop.name</code>.
     */
    public final TableField<StopRecord, String> NAME = createField(DSL.name("name"), SQLDataType.CLOB.nullable(false), this, "");

    private Stop(Name alias, Table<StopRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private Stop(Name alias, Table<StopRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.stop</code> table reference
     */
    public Stop(String alias) {
        this(DSL.name(alias), STOP);
    }

    /**
     * Create an aliased <code>public.stop</code> table reference
     */
    public Stop(Name alias) {
        this(alias, STOP);
    }

    /**
     * Create a <code>public.stop</code> table reference
     */
    public Stop() {
        this(DSL.name("stop"), null);
    }

    public <O extends Record> Stop(Table<O> path, ForeignKey<O, StopRecord> childPath, InverseForeignKey<O, StopRecord> parentPath) {
        super(path, childPath, parentPath, STOP);
    }

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    public static class StopPath extends Stop implements Path<StopRecord> {

        private static final long serialVersionUID = 1L;
        public <O extends Record> StopPath(Table<O> path, ForeignKey<O, StopRecord> childPath, InverseForeignKey<O, StopRecord> parentPath) {
            super(path, childPath, parentPath);
        }
        private StopPath(Name alias, Table<StopRecord> aliased) {
            super(alias, aliased);
        }

        @Override
        public StopPath as(String alias) {
            return new StopPath(DSL.name(alias), this);
        }

        @Override
        public StopPath as(Name alias) {
            return new StopPath(alias, this);
        }

        @Override
        public StopPath as(Table<?> alias) {
            return new StopPath(alias.getQualifiedName(), this);
        }
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<StopRecord> getPrimaryKey() {
        return Keys.STOP_PKEY;
    }

    private transient RouteStopPath _routeStop;

    /**
     * Get the implicit to-many join path to the <code>public.route_stop</code>
     * table
     */
    public RouteStopPath routeStop() {
        if (_routeStop == null)
            _routeStop = new RouteStopPath(this, null, Keys.ROUTE_STOP__ROUTE_STOP_STOP_ID_FKEY.getInverseKey());

        return _routeStop;
    }

    @Override
    public Stop as(String alias) {
        return new Stop(DSL.name(alias), this);
    }

    @Override
    public Stop as(Name alias) {
        return new Stop(alias, this);
    }

    @Override
    public Stop as(Table<?> alias) {
        return new Stop(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public Stop rename(String name) {
        return new Stop(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stop rename(Name name) {
        return new Stop(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public Stop rename(Table<?> name) {
        return new Stop(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stop where(Condition condition) {
        return new Stop(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stop where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stop where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stop where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stop where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stop where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stop where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public Stop where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stop whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public Stop whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
