/*
 * This file is generated by jOOQ.
 */
package app.cta4j.jooq.tables.records;


import app.cta4j.jooq.tables.Direction;
import org.jooq.Record1;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class DirectionRecord extends UpdatableRecordImpl<DirectionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.direction.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.direction.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>public.direction.name</code>.
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.direction.name</code>.
     */
    public String getName() {
        return (String) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached DirectionRecord
     */
    public DirectionRecord() {
        super(Direction.DIRECTION);
    }

    /**
     * Create a detached, initialised DirectionRecord
     */
    public DirectionRecord(Integer id, String name) {
        super(Direction.DIRECTION);

        setId(id);
        setName(name);
        resetChangedOnNotNull();
    }
}
